#ifndef BOARD_ALEPH_H_
#define BOARD_ALEPH_H_

#define PROBE_IO_RAW
#define PROBE_CDC_UART
#define PROBE_PIN_RESET 18

// PIO config
#define PROBE_SM 0
#define PROBE_PIN_OFFSET 19
#define PROBE_PIN_SWCLK (PROBE_PIN_OFFSET + 0) // GPIO 19
#define PROBE_PIN_SWDIO (PROBE_PIN_OFFSET + 1) // GPIO 20

// UART config
#define PROBE_UART_TX 24
#define PROBE_UART_RX 25
#define PROBE_UART_INTERFACE uart1
#define PROBE_UART_BAUDRATE 115200

#define PROBE_USB_CONNECTED_LED 17
#define PROBE_DAP_CONNECTED_LED 16
#define PROBE_DAP_RUNNING_LED 12
#define PROBE_UART_RX_LED 15
#define PROBE_UART_TX_LED 14

#define PROBE_PRODUCT_STRING "Aleph FC Debug Probe"

#endif
